---
- name: Install docker & requirements
  hosts: cloud-1
  become: yes
  roles:
    - role: roles/install_docker
    - role: roles/run_docker
    - role: roles/systemctl_config
  vars_files:
    - roles/run_docker/vars/main.yml